version: '3.9'
services:
  postgres-db: 
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
  
  registry:
    image: python:3.8-slim
    entrypoint: ["/bin/bash"]
    tty: true
    working_dir: /code
    container_name: registry
    volumes:
      - ./:/code
    ports:
      - 2424:2424
      - 4242:4242
    depends_on:
      - postgres-db
    links:
      - postgres-db

