services:
  postgres-db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
  
  registry:
    build: .
    container_name: registry
    tty: true
    ports:
      - "2424:2424/tcp"
      - "4242:4242/udp"
    depends_on:
      postgres-db:
        condition: service_healthy
    links:
      - postgres-db